/**
 * lib/types.ts
 *
 * Shared TypeScript interfaces for all CRM data models.
 *
 * These types are used by:
 *   - lib/mysql/queries.ts  — return types for all DB functions
 *   - app/api/*             — API request/response shapes
 *   - components/*          — prop types for all content components
 *
 * All date fields are ISO-8601 strings (e.g. "2024-03-15T10:30:00.000Z").
 * mysql2 returns DATETIME columns as strings when dateStrings: true is set
 * in the pool config — this is required because JS Date objects cannot be
 * serialised from Next.js Server Components to Client Components.
 */

/** A CRM customer record. */
export interface Customer {
  /** UUID v4, generated by crypto.randomUUID() in the application layer. */
  id: string
  name: string
  email: string
  /** Optional — null if not provided. */
  phone: string | null
  /** Optional — null if not provided. */
  address: string | null
  /** Set once at account creation. Never updated. */
  member_since: string
  created_at: string
  updated_at: string
}

/** An inventory product. */
export interface Product {
  /** UUID v4, generated by crypto.randomUUID(). */
  id: string
  name: string
  /** Stock-keeping unit — must be unique across all products. */
  sku: string
  category: string
  /** Stored as DECIMAL(10,2) in MySQL; returned as JS number via decimalNumbers:true. */
  price: number
  /** Current on-hand quantity. */
  stock: number
  /** Dashboard shows a warning badge when stock < low_stock_threshold. */
  low_stock_threshold: number
  /** Optional free-text description. Null if not provided. */
  description: string | null
  /** Optional product image URL. Null if not provided. */
  image_url: string | null
  /** Controls whether the product appears in the orders dropdown. */
  status: 'active' | 'inactive'
  created_at: string
  updated_at: string
}

/**
 * A customer order.
 * The `customer` and `order_items` fields are populated by fetchOrders()
 * via JOIN — they are absent on the raw DB row type.
 */
export interface Order {
  /** UUID v4, generated by crypto.randomUUID(). */
  id: string
  /**
   * Nullable — orders can exist without a customer (walk-in / guest).
   * Set to NULL (not deleted) when the referenced customer is deleted.
   */
  customer_id: string | null
  total: number
  status: 'pending' | 'processing' | 'completed' | 'cancelled'
  created_at: string
  updated_at: string
  /** Populated by JOIN in fetchOrders(). Absent on raw INSERT/UPDATE results. */
  customer?: Customer | null
  /** Populated by a second batch query in fetchOrders(). */
  order_items?: HydratedOrderItem[]
}

/**
 * A single line item within an order.
 * `price` is a snapshot of the product price at the time of purchase —
 * it does not change if the product price is later updated.
 */
export interface OrderItem {
  id: string
  order_id: string
  /**
   * Nullable — set to NULL (not deleted) when the referenced product is deleted.
   * This preserves historical order data even after product removal.
   */
  product_id: string | null
  quantity: number
  /** Price per unit at time of order. Immutable after creation. */
  price: number
  created_at: string
  /** Populated by JOIN in fetchOrders(). */
  product?: Product | null
}

export type HydratedOrderItem = OrderItem & {
  product?: Product | null
}

export type HydratedOrder = Order & {
  customer: Customer | null
  order_items: HydratedOrderItem[]
}

/**
 * Aggregated statistics for the dashboard page.
 * Returned by getDashboardStats() which runs 6 parallel DB queries.
 */
export interface DashboardStats {
  totalCustomers: number
  totalProducts: number
  totalOrders: number
  /** Sum of `total` for all orders with status = 'completed'. */
  totalRevenue: number
  /** Products where stock < low_stock_threshold, ordered by stock ASC, limit 5. */
  lowStockProducts: Product[]
  /** 5 most recent orders with customer data, ordered by created_at DESC. */
  recentOrders: HydratedOrder[]
  pendingOrdersCount: number
}
